export interface ProviderMeta {
  name: string;
  /** URL template — {id} is replaced with external_id */
  url?: string;
  players: boolean;
  teams: boolean;
  coaches: boolean;
  competitions: boolean;
  seasons: boolean;
  source: "wikidata" | "custom";
}

export const PROVIDERS: Record<string, ProviderMeta> = {
  wikidata: {
    name: "Wikidata",
    url: "https://www.wikidata.org/wiki/{id}",
    players: true,
    teams: true,
    coaches: true,
    competitions: true,
    seasons: true,
    source: "wikidata",
  },
  transfermarkt: {
    name: "Transfermarkt",
    url: "https://www.transfermarkt.com/x/profil/spieler/{id}",
    players: true,
    teams: true,
    coaches: false,
    competitions: true,
    seasons: false,
    source: "wikidata",
  },
  fbref: {
    name: "FBref",
    url: "https://fbref.com/en/players/{id}/",
    players: true,
    teams: true,
    coaches: true,
    competitions: true,
    seasons: true,
    source: "wikidata",
  },
  soccerway: {
    name: "Soccerway",
    url: undefined,
    players: true,
    teams: true,
    coaches: true,
    competitions: false,
    seasons: false,
    source: "wikidata",
  },
  sofascore: {
    name: "SofaScore",
    url: "https://www.sofascore.com/player/{id}",
    players: true,
    teams: false,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "wikidata",
  },
  flashscore: {
    name: "Flashscore",
    url: undefined,
    players: true,
    teams: false,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "wikidata",
  },
  opta: {
    name: "Opta",
    url: undefined,
    players: true,
    teams: true,
    coaches: false,
    competitions: true,
    seasons: true,
    source: "custom",
  },
  opta_numeric: {
    name: "Opta (numeric)",
    url: undefined,
    players: false,
    teams: false,
    coaches: false,
    competitions: true,
    seasons: false,
    source: "wikidata",
  },
  fotmob: {
    name: "FotMob",
    url: "https://www.fotmob.com/players/{id}/",
    players: true,
    teams: true,
    coaches: true,
    competitions: true,
    seasons: false,
    source: "custom",
  },
  understat: {
    name: "Understat",
    url: "https://understat.com/player/{id}",
    players: true,
    teams: true,
    coaches: false,
    competitions: true,
    seasons: true,
    source: "custom",
  },
  whoscored: {
    name: "WhoScored",
    url: undefined,
    players: true,
    teams: false,
    coaches: true,
    competitions: true,
    seasons: false,
    source: "custom",
  },
  thesportsdb: {
    name: "TheSportsDB",
    url: "https://www.thesportsdb.com/player/{id}",
    players: true,
    teams: true,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "custom",
  },
  impect: {
    name: "Impect",
    url: undefined,
    players: true,
    teams: false,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "custom",
  },
  wyscout: {
    name: "Wyscout",
    url: undefined,
    players: true,
    teams: false,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "custom",
  },
  skillcorner: {
    name: "SkillCorner",
    url: undefined,
    players: true,
    teams: false,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "custom",
  },
  heimspiel: {
    name: "heim:spiel",
    url: undefined,
    players: true,
    teams: false,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "custom",
  },
  espn: {
    name: "ESPN",
    url: "https://www.espn.com/soccer/player/_/id/{id}/",
    players: true,
    teams: true,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "wikidata",
  },
  premier_league: {
    name: "Premier League",
    url: "https://www.premierleague.com/players/{id}/",
    players: true,
    teams: false,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "wikidata",
  },
  kicker: {
    name: "kicker",
    url: "https://www.kicker.de/spieler/{id}/",
    players: true,
    teams: true,
    coaches: false,
    competitions: false,
    seasons: false,
    source: "wikidata",
  },
};

/** Build a URL for a provider + ID, or null if no URL template exists */
export function providerUrl(provider: string, id: string): string | null {
  const meta = PROVIDERS[provider];
  if (!meta?.url) return null;
  return meta.url.replace("{id}", encodeURIComponent(id));
}
